- hosts: webservers
  become: true

  vars:
    pip_install_packages:
      - name: docker
    redmine_image: bitnami/redmine:latest
    redmine_port: 3000

  roles:
    - role: geerlingguy.pip
      tags: setup
    - role: geerlingguy.docker
      tags: setup

  tasks:
    - name: Generate .env file for Redmine
      template:
        src: templates/redmine.env.j2
        dest: /root/redmine.env
        mode: '0600'
      tags: deploy

    - name: Remove existing Redmine container
      community.docker.docker_container:
        name: redmine
        state: absent
      ignore_errors: yes
      tags: deploy

    - name: Deploy Redmine container
      community.docker.docker_container:
        name: redmine
        image: "{{ redmine_image }}"
        restart_policy: always
        ports:
          - "{{ redmine_port }}:3000"
        env_file: /root/redmine.env
      tags: deploy
    